name: Daily Price Fetch

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies manually
        run: npm install @supabase/supabase-js node-fetch@2

      - name: Run script
        run: node backend/cron-fetch.js
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
